### ISSUE TITLE
Sidebar elements

### ISSUE THREAD

**Issue by Suplanus** [hughbris/grav-theme-landed#7]
In your live demo there are this side elements:
![image](https://user-images.githubusercontent.com/2002916/69820388-4b8cb000-1201-11ea-8d80-da9b4431522a.png)

But in the `_demo` I can not see how to do this. Is it possible to set the images? Also dont understand that for `intro`.

**Comment by hughbris** [comment]
Sure, it's a little convoluted but very flexible :) It should possibly be documented.

In [`_demo/pages/01.home/home.md](https://github.com/hughbris/grav-theme-landed/blob/develop/_demo/pages/01.home/home.md#l24), line 24 (which I don't seem to be able to link to directly), there is:

```yaml
features:
    items:
        '@taxonomy.pagetype': 'feature'
    order:
        by: default
```
which is defining a Grav collection called 'features', made up of every page tagged 'feature' in the taxonomy vocabulary 'pagetype', so any page with `taxonomy.pagetype: feature` in the frontmatter.

Let's take the page you can see in the screenshot, [`right-sidebar.md`](https://github.com/hughbris/grav-theme-landed/blob/develop/_demo/pages/02.layouts/04.right-sidebar/right-sidebar.md). It has that in its frontmatter, and then these items as well in its frontmatter:

```yaml
spotlight:
  image: 'images/pic04.jpg' # spotlight.jpg
  headline: 'Interdum felis blandit praesent sed augue'
  subheading: 'Nunc commodo accumsan eget id nisi eu col volutpat magna'
  blurb: 'Feugiat accumsan lorem eu ac lorem amet ac arcu phasellus tortor enim mi mi nisi praesent adipiscing. Integer mi sed nascetur cep aliquet augue varius tempus lobortis porttitor lorem et accumsan consequat adipiscing lorem.'
  # button:
  #  text: 'Learn More'
```

This is where that info is pulled from. **So the direct answer to your question is `spotlight.image` in every page tagged pagetype='feature'. Change that for a different image.**

You could redefine that collection 'features' in the homepage if you want, using a taxonomy query, a fixed list of pages, or any of the [methods available for defining a Grav collection](https://learn.getgrav.org/16/content/collections#page-collections).

If you look at how this works in Twig, you can see `home.html.twig` just [loads the collection based on its name](https://github.com/hughbris/grav-theme-landed/blob/3e0fbf3fe7137eb2573293272d60aa952dbc839c/templates/home.html.twig#L13), then [calls `partials/sections/features.html.twig` on each feature item](https://github.com/hughbris/grav-theme-landed/blob/3e0fbf3fe7137eb2573293272d60aa952dbc839c/templates/home.html.twig#L21).

That template [checks for `image` in the frontmatter under `spotlight`](https://github.com/hughbris/grav-theme-landed/blob/3e0fbf3fe7137eb2573293272d60aa952dbc839c/templates/partials/sections/feature.html.twig#L5) and has a fallback too.

A bit quick but I hope that explains it.
